# Generated by Django 5.1.1 on 2024-10-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('type_of_employment', models.CharField(max_length=100)),
                ('military_service_status', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('minimum_educational_qualification', models.CharField(max_length=100)),
                ('job_skill', models.CharField(max_length=100)),
                ('level_of_proficiency', models.CharField(max_length=100)),
                ('benefits_and_facilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KarfarmaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='KarjoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website_address', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('about', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('activity_area', models.TextField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True)),
                ('profile_background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('media', models.FileField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karfarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='karbridge_app.karfarmaprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='درباره من')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('marital_status', models.CharField(max_length=20, verbose_name='وضعیت تاهل')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('state', models.CharField(max_length=100, verbose_name='استان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('educational_level', models.CharField(max_length=100, verbose_name='سطح تحصیلات')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('university_name', models.CharField(max_length=255, verbose_name='نام دانشگاه/مؤسسه')),
                ('education_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تحصیلات')),
                ('education_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تحصیلات')),
                ('organization_name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('job_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع کار')),
                ('job_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان کار')),
                ('skill', models.CharField(max_length=100, verbose_name='مهارت')),
                ('proficiency_level', models.CharField(max_length=100, verbose_name='سطح تسلط')),
                ('instagram_address', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام')),
                ('linkedin_address', models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین')),
                ('github_address', models.URLField(blank=True, null=True, verbose_name='آدرس گیت\u200cهاب')),
                ('resume_attachment', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='بارگذاری رزومه')),
                ('karjo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='karbridge_app.karjoprofile')),
            ],
        ),
    ]
