# Generated by Django 5.1.1 on 2024-10-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbridge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits_And_Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_level', models.CharField(max_length=100, verbose_name='سطح تحصیلات')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('university_name', models.CharField(max_length=255, verbose_name='نام دانشگاه/مؤسسه')),
                ('education_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تحصیلات')),
                ('education_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تحصیلات')),
            ],
        ),
        migrations.CreateModel(
            name='Job_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job_skill_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('job_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع کار')),
                ('job_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان کار')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='level_of_proficiency',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_start_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_start_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='benefits_and_facilities',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('remote', 'دورکاری'), ('internship', 'کارآموزی'), ('project_based', 'پروژه ای')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='gender',
            field=models.CharField(choices=[('no_body', 'مهم نیست'), ('male', 'مرد'), ('female', 'زن')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='job_skill',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='military_service_status',
            field=models.CharField(choices=[('no_matter', 'مهم نیست'), ('completed', 'پایان خدمت'), ('student_exemption', 'معافیت تحصیلی'), ('permanent_exemption', 'معافیت دائم')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='minimum_educational_qualification',
            field=models.CharField(choices=[('no_matter', 'مهم نیست'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(choices=[('negotiable', 'توافقی'), ('minimum_wage', 'حقوق پایه(وزارت کار)'), ('9_12_million', 'بین 9 تا 12 میلیون تومان'), ('12_20_million', 'بین 12 تا 20 میلیون تومان'), ('20_35_million', 'بین 20 تا 35 میلیون تومان'), ('35_60_million', 'بین 35 تا 60 میلیون تومان'), ('above_60_million', 'بالای 60 میلیون تومان')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='educational_level',
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits_and_facilities',
            field=models.ManyToManyField(blank=True, null=True, to='karbridge_app.benefits_and_facilities'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_skill',
            field=models.ManyToManyField(related_name='job_postings', to='karbridge_app.job_skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='educational_level',
            field=models.ManyToManyField(null=True, to='karbridge_app.educational_level'),
        ),
        migrations.AddField(
            model_name='resume',
            name='organization_name',
            field=models.ManyToManyField(null=True, to='karbridge_app.organization_name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(null=True, to='karbridge_app.job_skill_resume'),
        ),
    ]
