# Generated by Django 5.1.1 on 2024-10-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbridge_app', '0002_benefits_and_facilities_educational_level_job_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='benefits_and_facilities',
            field=models.ManyToManyField(to='karbridge_app.benefits_and_facilities'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='educational_level',
            field=models.ManyToManyField(to='karbridge_app.educational_level'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='organization_name',
            field=models.ManyToManyField(to='karbridge_app.organization_name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(to='karbridge_app.job_skill_resume'),
        ),
    ]
