# Generated by Django 5.1.1 on 2024-10-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbridge_app', '0003_alter_jobposting_benefits_and_facilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='karfarma',
            new_name='auther',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(blank=True, choices=[('digital_marketing', 'دیجیتال مارکتینگ'), ('SEO', 'سئو'), ('Graphic_Design_Animation', 'طراحی گرافیک / انیمیشن'), ('User_Interface_Design', 'طراحی رابط کاربری'), ('user_experience', 'تجربه کاربری')], max_length=25),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_history',
            field=models.CharField(blank=True, choices=[('no_mater', 'مهم نیست'), ('One_to_two', '1 تا 2 سال'), ('two_to_four', '2 تا 4 سال'), ('four_to_six', '4تا 6 سال'), ('more_six', 'بیشتر از 6 سال')], max_length=25),
        ),
        migrations.AddField(
            model_name='organization',
            name='addres_organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('remote', 'دورکاری'), ('internship', 'کارآموزی'), ('project_based', 'پروژه ای')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='gender',
            field=models.CharField(choices=[('no_body', 'مهم نیست'), ('male', 'مرد'), ('female', 'زن')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='military_service_status',
            field=models.CharField(choices=[('no_matter', 'مهم نیست'), ('completed', 'پایان خدمت'), ('student_exemption', 'معافیت تحصیلی'), ('permanent_exemption', 'معافیت دائم')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='minimum_educational_qualification',
            field=models.CharField(choices=[('no_matter', 'مهم نیست'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(choices=[('negotiable', 'توافقی'), ('minimum_wage', 'حقوق پایه(وزارت کار)'), ('9_12_million', 'بین 9 تا 12 میلیون تومان'), ('12_20_million', 'بین 12 تا 20 میلیون تومان'), ('20_35_million', 'بین 20 تا 35 میلیون تومان'), ('35_60_million', 'بین 35 تا 60 میلیون تومان'), ('above_60_million', 'بالای 60 میلیون تومان')], max_length=25),
        ),
        migrations.AlterField(
            model_name='organization',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
