# Generated by Django 5.1.1 on 2024-11-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbridge_app', '0005_remove_resume_about_organization_name_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_skill',
            name='proficiency_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
