# Generated by Django 5.1.1 on 2024-11-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbridge_app', '0006_alter_job_skill_proficiency_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='job_category',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='karbridge_app.jobcategory'),
        ),
    ]
